name: xHomes
version: '1.0.2'
main: org.curryman.xhomes.XHomes
api-version: '1.17'
commands:
  homes:
    description: Player command for the plugin
  home:
    description: Player command for plugin
  xhomes:
    description: Admin commands for the plugin


permissions:
  xhomes.gui:
    description: Let players open the GUI
    default: not op
  xhomes.individual:
    description: Let players teleport to individual homes via commands (NOT the GUI)
    default: not op
  xhomes.cooldown-bypass:
    description: Let players instantly teleport to their homes, with no cooldown
    default: op
  xhomes.admin:
    description: Let players use admin commands
    default: op


softdepend:
  - HeadDatabase
